/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import java.io.IOException;

public class MiningControllerTest {

	@Test public void testReturnBalance() {
    		final MiningController miningController = new MiningController();
        assertEquals("Value for the Debug mode", "50000.00", miningController.returnBalance());
    }

	@Test public void testReturnHashrate() {
		final MiningController miningController = new MiningController();
		assertEquals("Value for the Debug mode", "8000", miningController.returnHashrate());
	}

	@Test public void testJonParse() {
		final MiningController miningController = new MiningController();
		final String sampleJson = "{\"status\":true,\"data\":{\"hashrate\":8000,\"balance\":50}}";
		assertEquals("balance", "50", miningController.jsonParse(sampleJson, "balance"));
		assertEquals("hashrate", "8000", miningController.jsonParse(sampleJson, "hashrate"));
	}

	@Test public void testClaymoreStarter() throws IOException {
		final MiningController miningController = new MiningController();
		miningController.claymoreStarter();
		try { Thread.sleep(300000); } catch (InterruptedException e) {}
	}
}
