/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import java.io.IOException;

public class MiningControllerTest {

	@Test public void testReturnBalance() throws IOException {
    		MiningController miningController = new MiningController();
        assertEquals("Value for the Debug mode", "50000.0", miningController.returnBalance());
    }

	@Test public void testReturnHashrate() throws IOException {
		MiningController miningController = new MiningController();
		assertEquals("Value for the Debug mode", "8000", miningController.returnHashrate());
	}
}
