/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import java.awt.GridLayout;

import javax.swing.JFrame;

public class QRScannerTest {

	@Test public void testShowScanner() throws InterruptedException {
		JFrame newFrame = new JFrame();
		newFrame.setSize(600, 400);
		newFrame.setLayout(new GridLayout(1, 1));
		newFrame.setResizable(true);
    		final QRScanner qrScanner = new QRScanner();
    		assertNotNull("QRScanner", qrScanner);
    		qrScanner.showScanner(newFrame);
    		newFrame.setVisible(true);
		final String qrCodeText = qrScanner.scanCodeContinuously();
		assertNotNull("QR Code", qrCodeText);
		//Thread.sleep(60000);
    }
}
